### ISSUE TITLE
Create a database table

### ISSUE THREAD

**Issue by jaltman-1** [tlevin1/Reccomendation-Portal#30]
POINTS: 5

Test link: https://github.com/tlevin1/Reccomendation-Portal/blob/develop/src/LOR/test_models.py

**Comment by tlevin1** [comment]
The goal of this task is to create and implement a database table with the required fields. If possible to test that the table can be deployed and tested.

**Comment by EdwinTrejo** [comment]
Create models, fields, classes, that show the relationship of the data types we will make use of in the project
