### ISSUE TITLE
As a letter writer, I want to accept or deny requests.

### ISSUE THREAD

**Issue by EdwinTrejo** [tlevin1/Reccomendation-Portal#6]
POINT: 13

in order to accept or deny, there should be a button "accept" or "deny", once press, there should be a category in database that will keep the answer.

**Comment by EdwinTrejo** [comment]
from the same HTML site a way to create a submission to change the status of an item. This would relate to the task https://github.com/tlevin1/Reccomendation-Portal/issues/5

**Comment by jaltman-1** [comment]
Show changed status of request
